apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codefresh-argocd-hooks
  annotations:
    argocd.argoproj.io/hook: PreSync
subjects:
  - kind: ServiceAccount
    name: default
    namespace: guestbook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argohooks-rollots-configmap-applications-view
