apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codefresh-list-rollouts
  annotations:
    argocd.argoproj.io/hook: PreSync
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollots-view
