apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
          - name: test1sdasdsdsdasdfaasasdasdasasdfasdfaf
            value: testasdasd
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ui-2
  template:
    metadata:
      labels:
        app: ui-2
    spec:
      containers:
      # - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
      - image: busybox
        name: ui-2
        ports:
        - containerPort: 80
        env:
          - name: version2
            value: testasdasdasdasdasdfasdasdasdf
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 1
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
