apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  # args:
  # - name: application-name  
  metrics:
  - name: success-rate
    interval: 10s
    count: 1
    failureLimit: 1
    failureCondition: result.errorRate > 0.0051
    successCondition: result.errorRate <= 0.005
    provider:
      newRelic:
        profile: newrelic-v2  # optional, defaults to 'newrelic'
        query: |
          SELECT count(apm.service.error.count) / count(apm.service.transaction.duration) as errorRate FROM Metric WHERE (appName = 'api-events') AND (transactionType = 'Web') 