apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  # args:
  # - name: application-name
  metrics:
  - name: success-rate
    interval: 10s
    count: 1
    failureLimit: 3
    failureCondition: result.successRate < 0.95
    successCondition: result.successRate >= 0.95
    provider:
      newRelic:
        profile: newrelic-v2  # optional, defaults to 'newrelic'
        query: |
          FROM Transaction SELECT percentage(count(*), WHERE httpResponseCode != 500) as successRate where appName = 'api-events'