apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  # args:
  # - name: application-name
  metrics:
  - name: success-rate
    interval: 10s
    count: 1
    failureLimit: 1
    failureCondition: result.errorRate > 0.051
    successCondition: result.errorRate <= 0.05
    provider:
      newRelic:
        profile: newrelic-v2  # optional, defaults to 'newrelic'
        query: |
          FROM Metric SELECT count(apm.service.error.count) / count(apm.service.transaction.duration) as 'errorRate'  WHERE (appName = 'api-events') AND (transactionType = 'Web') LIMIT MAX SINCE 1800 seconds AGO TIMESERIES