apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: failed
  template:
    metadata:
      labels:
        app: failed
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.212312
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
          - name: test1sdasd
            value: testasdasd
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 1
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 101
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
