apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 0
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
          - name: test
            value: test
          - name: test2
            value: test
          - name: test3
            value: test
          - name: test4
            value: test
          - name: test5
            value: test
          - name: test6
            value: test
          - name: sadfsdnaaaaaqaa8912qwq
            value: test
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
          # - name: test2
          #   value: test2



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: chrome-issue
# spec:
#   replicas: 1
#   revisionHistoryLimit: 3
#   selector:
#     matchLabels:
#       app: chrome-issue
#   template:
#     metadata:
#       labels:
#         app: chrome-issue
#     spec:
#       containers:
#       - image: codefresh/ui-e2e-image
#         name: chrome-issue
#         command: ["/bin/sh"]
#         args: ["-c", "while true; do echo hello; sleep 10;done"]
#         ports:
#         - containerPort: 80
