apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: curlimages/curl
        command:
          - "sleep"
          - "hello world"
      restartPolicy: Never
  backoffLimit: 2
