apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-guestbook-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Rollout
    name: rollout-ref-deployment-guestbook
  minReplicas: 5
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
