apiVersion: batch/v1
kind: Job
metadata:
  name: clone-git-pre-sync
  namespace: guestbook
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: git-clone
        image: bitnami/git
        command:
          - "sleep"
          - "3600"
        env:
          - name: gihub-token
            valueFrom:
              secretKeyRef:
                key: github-token
                name: github-token
        volumeMounts:
        - name: git-repo-source
          mountPath: "/tmp/source"
      volumes:
      - name: git-repo-source
        persistentVolumeClaim:
          claimName: git-repo-source
      restartPolicy: Never
  backoffLimit: 1



# apiVersion: argoproj.io/v1alpha1
# kind: WorkflowTemplate
# metadata:
#   # creationTimestamp: null
#   name: clone-git-pre-sync
  # namespace: codefresh-v2
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
# spec:
#   arguments: {}
#   entrypoint: whalesay
#   templates:
#   - container:
#       args:
#       - Hello World
#       command:
#       - cowsay
#       image: docker/whalesay
#       name: ""
#       resources: {}
#     inputs: {}
#     metadata: {}
#     name: whalesay
#     outputs: {}

### not workflows problem with rbac ask Vadim tomorrow
# apiVersion: argoproj.io/v1alpha1
# kind: Workflow
# metadata:
#   name: clone-git-pre-sync
#   namespace: codefresh-v2
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
# spec:
#   entrypoint: whalesay        # Defines "whalesay" as the "main" template
#   templates:
#   - name: whalesay            # Defining the "whalesay" template
#     container:
#       image: curlimages/curl
#       command: [echo]
#       args: ["hello world"]
