apiVersion: batch/v1
kind: Job
metadata:
  name: clone-git-pre-sync
  namespace: guestbook
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: git-clone
        image: bitnami/git
        # command: [ "/bin/bash", "-c" , "sleep 3600" ]
        command: [ "/bin/bash" ]
        args:
          - "-c"
          - cd /tmp/source && rm -rf argocd-example-apps && git clone https://"$token"@github.com/Konstantin-petrenko/argocd-example-apps.git && ls -la && cd argocd-example-apps && git show HEAD~1 | grep commit | awk '{print $2}' > /tmp/source/stable_commit
        env:
          - name: token
            valueFrom:
              secretKeyRef:
                name: github-token
                key: github-token
        volumeMounts:
          - name: git-repo-source
            mountPath: "/tmp/source"
      volumes:
      - name: git-repo-source
        persistentVolumeClaim:
          claimName: git-repo-source
      restartPolicy: Never
  backoffLimit: 1

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: pi
# spec:
#   template:
#     spec:
#       containers:
#       - name: pi
#         image: perl
#         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
#       restartPolicy: Never
#   backoffLimit: 4

# apiVersion: argoproj.io/v1alpha1
# kind: WorkflowTemplate
# metadata:
#   # creationTimestamp: null
#   name: clone-git-pre-sync
  # namespace: codefresh-v2
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
# spec:
#   arguments: {}
#   entrypoint: whalesay
#   templates:
#   - container:
#       args:
#       - Hello World
#       command:
#       - cowsay
#       image: docker/whalesay
#       name: ""
#       resources: {}
#     inputs: {}
#     metadata: {}
#     name: whalesay
#     outputs: {}

### not workflows problem with rbac ask Vadim tomorrow
# apiVersion: argoproj.io/v1alpha1
# kind: Workflow
# metadata:
#   name: clone-git-pre-sync
#   namespace: codefresh-v2
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
# spec:
#   entrypoint: whalesay        # Defines "whalesay" as the "main" template
#   templates:
#   - name: whalesay            # Defining the "whalesay" template
#     container:
#       image: curlimages/curl
#       command: [echo]
#       args: ["hello world"]
