apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-ref-deployment-guestbook
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: argo-notifications
spec:
  # replicas: 5
  progressDeadlineAbort: true
  progressDeadlineSeconds: 40
  minReadySeconds: 10
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui
  # namespace: argocd
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
      # analysis:
      #   templates:
      #   # - templateName: random-fail
      #   - templateName: pass
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: argo-combined-app
# spec:
#   args:
#   - name: service-name
#   metrics:
#   - name: success-rate
#     interval: 10s
#     successCondition: result[0] >= 0.8
#     failureCondition: result[0] < 0.8
#     failureLimit: 3
#     provider:
#       prometheus:
#         address: http://prometheus-server.monitoring
#         query: |
#           sum(irate(
#             istio_requests_total{
#               reporter="source",
#               destination_service=~"{{args.service-name}}",
#               response_code=~"2.*"
#             }[2m]
#           )) / sum(irate(
#             istio_requests_total{
#               reporter="source",
#               destination_service=~"{{args.service-name}}"
#             }[2m]
#           ))
