apiVersion: batch/v1
kind: Job
metadata:
  name: test-post-sync
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: curlimages/curl
        command:
          - "echo"
          - "hello world"
      restartPolicy: Never
  backoffLimit: 1
