apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: roll-ui-1
spec:
  progressDeadlineAbort: true
  progressDeadlineSeconds: 40
  minReadySeconds: 10

  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
          - name: version2asd
            value: test
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 1
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
